---

- name: copy venv wrapper to run command in virtualenv to vm
  template: src=venv_exec.j2 dest={{ mz_venv }}/bin/pyenv mode=0755

#create mezzanine project
- name: mkdir project path {{ mz_project_path }}
  command: mkdir -p {{ mz_project_path }}

- name: create mezzanine project {{ mz_project_path }}/{{ mz_project_name }}
  command: chdir={{ mz_project_path }}
           {{ mz_venv }}/bin/pyenv 
           mezzanine-project {{ mz_project_name }}

#set up local_settings.py
- name: backup local_settings.py
  command: chdir={{ mz_project_path }}/{{ mz_project_name }}
           creates=local_settings.py.orig
           mv local_settings.py local_settings.py.orig

- name: copy local_settings.py to vm
  template: src=local_settings.j2 dest={{ mz_project_path }}/{{ mz_project_name }}/mz_settings.py

- name: get secret key and never cache key
  shell: chdir={{ mz_project_path }}/{{ mz_project_name }} 
         rm -rf tp-keys && 
         grep SECRET_KEY local_settings.py.orig >> tp-keys &&
         grep NEVERCACHE_KEY local_settings.py.orig >> tp-keys

- name: cat to produce local_settings.py
  shell: chdir={{ mz_project_path }}/{{ mz_project_name }} 
         cat mz_settings.py tp-keys > local_settings.py &&
         rm mz_settings.py tp-keys

#mezzanine project initialization
- name: python manage.py createdb 
  command: chdir={{ mz_project_path }}/{{ mz_project_name }}
           {{ mz_venv }}/bin/pyenv
           python manage.py createdb --noinput

- name: python manage.py collectstatic
  command: chdir={{ mz_project_path }}/{{ mz_project_name }}
           {{ mz_venv }}/bin/pyenv
           python manage.py collectstatic --noinput

