--- 

- name: update apt cache and upgrade
  apt: update_cache=yes #upgrade=dist

- name: install packages 
  apt: pkg={{ item }} state=latest
  with_items:
    - nginx
    - uwsgi
    - uwsgi-extra
    - uwsgi-plugin-python
    - postgresql
    - postgresql-client
    #for ansible postgresql modules and building psycopg2 in virtualenv
    - python2.7-dev
    - postgresql-server-dev-9.3 
    - python-psycopg2
    - python-virtualenv
    - python-pip
  notify:
    - start nginx 
    - start postgresql

- name: apt-get clean
  command: apt-get clean

- name: copy pg_hba.conf to vm
  copy: src=pg_hba.conf dest=/etc/postgresql/9.3/main/pg_hba.conf
        owner=postgres group=postgres mode=0640

- name: restart postgresql
  service: name=postgresql state=restarted

