---
# handlers file for ansible-mezzanine

- name: start apache2
  service: name=apache2 state=started enabled=yes

- name: restart apache2
  service: name=apache2 state=restarted 

- name: start postgresql
  service: name=postgresql state=started enabled=yes

- name: restart postgresql
  service: name=postgresql state=restarted
