---
# handlers file for ansible-mezzanine

- name: start apache2
  service: name=apache2 state=started enabled=yes

- name: restart apache2
  service: name=apache2 state=restarted 

- name: start nginx
  service: name=nginx state=started enabled=yes

- name: restart nginx 
  service: name=nginx state=restarted 

- name: start uwsgi 
  service: name=uwsgi state=started enabled=yes

- name: restart uwsgi 
  service: name=uwsgi state=restarted 

- name: start postgresql
  service: name=postgresql state=started enabled=yes

- name: restart postgresql
  service: name=postgresql state=restarted
